FROM python:3.12

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./controller_reconcile /code/app

# To enable debug logging, set to 1
ENV DEBUG 0

CMD ["python3", "/code/app/reconcile.py"]
