---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validating-webhook
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validating-webhook
  template:
    metadata:
      labels:
        app: validating-webhook
    spec:
      replicas: {{ .Values.replicaCount }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-validating-webhook
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.validationWebhook.repository }}:{{ .Values.image.validationWebhook.tag }}"
          imagePullPolicy: {{ .Values.image.validationWebhook.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if gt ( int .Values.service.tlsEnabled ) 0 }}
            {{- with .Values.tlsVolumeMounts }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- end }}
          env:
          {{- with .Values.service }}
          - name: SSL_CERTIFICATE_FILE
            value: {{ .tlsCertificateFile }}
          - name: SSL_KEY_FILE
            value: {{ .tlsKeyFile }}
          - name: USE_TLS
            value: {{ .tlsEnabled | quote }}
          {{- end }}
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: {{ .Values.service.port | quote }}
          - name: WORKERS
            value: {{ .Values.service.workers | quote }}
      {{- if gt ( int .Values.service.tlsEnabled ) 0 }}
        {{- with .Values.tlsVolumes }}
          {{- toYaml . | nindent 6 }}
        {{- end }}
      {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutating-webhook
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutating-webhook
  template:
    metadata:
      labels:
        app: mutating-webhook
    spec:
      replicas: {{ .Values.replicaCount }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-mutating-webhook
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.mutationWebhook.repository }}:{{ .Values.image.mutationWebhook.tag }}"
          imagePullPolicy: {{ .Values.image.mutationWebhook.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if gt ( int .Values.service.tlsEnabled ) 0 }}
            {{- with .Values.tlsVolumeMounts }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- end }}
          env:
          {{- with .Values.service }}
          - name: SSL_CERTIFICATE_FILE
            value: {{ .tlsCertificateFile }}
          - name: SSL_KEY_FILE
            value: {{ .tlsKeyFile }}
          - name: USE_TLS
            value: {{ .tlsEnabled | quote }}
          {{- end }}
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: {{ .Values.service.port | quote }}
          - name: WORKERS
            value: {{ .Values.service.workers | quote }}
      {{- if gt ( int .Values.service.tlsEnabled ) 0 }}
        {{- with .Values.tlsVolumes }}
          {{- toYaml . | nindent 6 }}
        {{- end }}
      {{- end }}
