---
apiVersion: v1
kind: Service
metadata:
  name: validating-webhook
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: validating-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: mutating-webhook
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mutating-webhook
