# Target namespace to deploy the webhooks in
namespace: default

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 2

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  validationWebhook:
    repository: ghcr.io/nicc777/kubernetes-recipes/admission-validation-webhook
    pullPolicy: IfNotPresent
    tag: "validation-webhook-r0.17"
  mutationWebhook:
    repository: ghcr.io/nicc777/kubernetes-recipes/admission-mutation-webhook
    pullPolicy: IfNotPresent
    tag: "mutation-webhook-r0.14"
  controller:
    repository: ghcr.io/nicc777/kubernetes-recipes/auto-httproute-controller
    pullPolicy: IfNotPresent
    tag: "ah-controller-r0.1"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8443

# Application settings - will be applied to both web hook deployments
applicationSettings:
  webhooks:
    tlsEnabled: 1
    tlsKeyFile: /certs/tls.key
    tlsCertificateFile: /certs/tls.crt
    workers: "4"
    debug: 0
  controller:
    debug: 0
    policyStrategy: strict-no-unmanaged-httproutes

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 1000m
    memory: 512Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  webhooks:
    tcpSocket:
      port: 8443
    initialDelaySeconds: 3
    periodSeconds: 3
    failureThreshold: 3
  controller:
    exec:
      command:
        - /bin/true
    initialDelaySeconds: 3
    periodSeconds: 3
readinessProbe:
  webhooks:
    tcpSocket:
      port: 8443
    initialDelaySeconds: 3
    periodSeconds: 3
    failureThreshold: 3
  controller:
    exec:
      command:
        - /bin/true
    initialDelaySeconds: 3
    periodSeconds: 3

tlsVolumeMounts:
  volumeMounts:
    - name: tls
      mountPath: /certs
      readOnly: true

tlsVolumes:
  volumes:
    - name: tls
      secret:
        secretName: auto-httproute-cert
