---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: auto-httproute-create-task
  namespace: bootstrapping
spec:
  workspaces:
  - name: shared-data
    mountPath: /data/general
  # - name: ws-env
  #   mountPath: /data/.env
  steps:
  - name: prepare-application-manifest
    image: bitnami/kubectl:latest
    script: |
      #!/usr/bin/env bash
      cat <<EOF > $(workspaces.shared-data.path)/admission-webhook-application.yaml
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: auto-httproute-admission-webhooks
        namespace: argocd
        finalizers:
          - resources-finalizer.argocd.argoproj.io
        labels:
          name: admission-webhooks
      spec:
        project: default
        source:
          repoURL: https://github.com/nicc777/kubernetes-recipes.git
          targetRevision: 3-finish-admission-webhooks
          path: admission_webhooks/charts/auto_httproute
          helm:
            valuesObject:
              applicationSettings:
                tlsEnabled: 1
                debug: 1
              image:
                validationWebhook:
                  tag: validation-webhook-r0.6
                mutationWebhook:
                  tag: mutation-webhook-r0.3
            skipCrds: false
            skipSchemaValidation: false
        destination:
          server: https://kubernetes.default.svc
          namespace: default
        info:
          - name: 'Repo:'
            value: 'https://github.com/nicc777/kubernetes-recipes'
        syncPolicy:
          automated:
            # enable: true
            prune: true
            selfHeal: true
            allowEmpty: false
          syncOptions:
          - Validate=false
          - CreateNamespace=false
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
          - SkipDryRunOnMissingResource=true
          - Replace=true
          retry:
            limit: 5
            backoff:
              duration: 5s
              factor: 2
              maxDuration: 3m
        revisionHistoryLimit: 10

      EOF
  - name: deploy-application
    image: bitnami/kubectl:latest
    script: |
      #!/usr/bin/env bash
      kubectl apply -f $(workspaces.shared-data.path)/admission-webhook-application.yaml
      sleep 30

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: auto-httproute-create-end-task
  namespace: bootstrapping
spec:
  workspaces:
  - name: shared-data
    mountPath: /data/general
  # - name: ws-env
  #   mountPath: /data/.env
  steps:
  - name: get-ca-bundle-data
    image: bitnami/kubectl:latest
    script: |
      #!/usr/bin/env bash
      kubectl get secrets -n default
      echo "----------------------------------------"
      export CA_BUNDLE=$(kubectl get secret auto-httproute-cert -n default -o jsonpath='{.data.ca\.crt}')
      echo "CA Bundle:"
      echo
      echo $CA_BUNDLE
      echo "----------------------------------------"
  - name: print-done-message
    image: bitnami/kubectl:latest
    script: |
      #!/usr/bin/env bash
      echo "----------------------------------------"
      echo "Created Files:"
      echo "----------------------------------------"
      echo
      ls -lahrt $(workspaces.shared-data.path)/*.yaml
      echo
      echo "----------------------------------------"
      echo "Namespaces:"
      echo "----------------------------------------"
      echo
      kubectl get namespaces
      echo
      echo "----------------------------------------"
      echo "ArgoCD Applications:"
      echo "----------------------------------------"
      echo
      kubectl get applications -n argocd
      echo
      echo "----------------------------------------"
      echo "Admission Web Hook Application:"
      echo "----------------------------------------"
      echo
      kubectl describe application/auto-httproute-admission-webhooks -n argocd
      echo
      echo "----------------------------------------"
      echo
      echo "DONE !!!"
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: auto-httproute-admission-webhook-create-pipeline
  namespace: bootstrapping
spec:
  workspaces:
  - name: shared-data
  tasks:
  - name: run-auto-httproute-create-task
    taskRef:
      name: auto-httproute-create-task
    workspaces:
    - name: shared-data
  - name: run-auto-httproute-create-end-task
    runAfter:
    - run-auto-httproute-create-task
    taskRef:
      name: auto-httproute-create-end-task
    workspaces:
    - name: shared-data
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: auto-httproute-admission-webhook-create-run
  namespace: bootstrapping
spec:
  serviceAccountName: tekton-cluster-admin-sa
  pipelineRef:
    name: auto-httproute-admission-webhook-create-pipeline
  workspaces:
  - name: shared-data
    persistentVolumeClaim:
      claimName: shared-task-storage
