---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-example001
  namespace: example001
provisioner: nfs.csi.k8s.io
parameters:
  server: ${NFS_SERVER_HOST}
  share: /websites/examples/static_01/website-placeholder
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
- hard
- nfsvers=4.1
