---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-example001
  namespace: example001
provisioner: nfs.csi.k8s.io
parameters:
  server: ${NFS_SERVER_HOST}          # Use this command to do environment variable substitution: envsubst < persisted_volumes/example001/sc-nfs.yaml | kubectl apply -f -
  share: /websites/examples/static_01
  subDir: website-placeholder         # If this is not present, a random sub-directory will be created starting with "pvc-"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
- hard
- nfsvers=4.1
